name: Publish Package (DRY RUN)

on:
  pull_request:
    types: [opened]

jobs:
  build-and-publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Clear NPM cache
        run: npm cache clean --force

      - name: Install dependencies and build
        run: npm ci

      - name: Make release
        run: npm run build
        id: makeRelease

      - name: Fail job if makeRelease failed
        if: steps.makeRelease.outcome == 'failure'
        run: exit 1

        id: check-build-status
      - name: Publish NPM package (regular)
        if: "!github.event.release.prerelease"
        run: |
          npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Publish NPM package (pre-release)
        if: "github.event.release.prerelease"
        run: |
          npm publish --tag next --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
